turtle.pendown()
turtle.pensize(6)
turtle.pencolor("green")
turtle.seth(60)
turtle.fd(120)
turtle.seth(-60import turtle
turtle.penup()
turtle.fd(-60)
)
turtle.fd(120)
turtle.seth(-180)
turtle.fd(120)
